//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 11:55:08 PM ICT 
//


package objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Students"/&gt;
 *         &lt;element ref="{}Classes"/&gt;
 *         &lt;element ref="{}Subjects"/&gt;
 *         &lt;element ref="{}Teachers"/&gt;
 *         &lt;element ref="{}StudentSubjects"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "students",
    "classes",
    "subjects",
    "teachers",
    "studentSubjects"
})
@XmlRootElement(name = "Infomation")
public class Infomation {

    @XmlElement(name = "Students", required = true)
    protected Students students;
    @XmlElement(name = "Classes", required = true)
    protected Classes classes;
    @XmlElement(name = "Subjects", required = true)
    protected Subjects subjects;
    @XmlElement(name = "Teachers", required = true)
    protected Teachers teachers;
    @XmlElement(name = "StudentSubjects", required = true)
    protected StudentSubjects studentSubjects;

    /**
     * Gets the value of the students property.
     * 
     * @return
     *     possible object is
     *     {@link Students }
     *     
     */
    public Students getStudents() {
        return students;
    }

    /**
     * Sets the value of the students property.
     * 
     * @param value
     *     allowed object is
     *     {@link Students }
     *     
     */
    public void setStudents(Students value) {
        this.students = value;
    }

    /**
     * Gets the value of the classes property.
     * 
     * @return
     *     possible object is
     *     {@link Classes }
     *     
     */
    public Classes getClasses() {
        return classes;
    }

    /**
     * Sets the value of the classes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classes }
     *     
     */
    public void setClasses(Classes value) {
        this.classes = value;
    }

    /**
     * Gets the value of the subjects property.
     * 
     * @return
     *     possible object is
     *     {@link Subjects }
     *     
     */
    public Subjects getSubjects() {
        return subjects;
    }

    /**
     * Sets the value of the subjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subjects }
     *     
     */
    public void setSubjects(Subjects value) {
        this.subjects = value;
    }

    /**
     * Gets the value of the teachers property.
     * 
     * @return
     *     possible object is
     *     {@link Teachers }
     *     
     */
    public Teachers getTeachers() {
        return teachers;
    }

    /**
     * Sets the value of the teachers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Teachers }
     *     
     */
    public void setTeachers(Teachers value) {
        this.teachers = value;
    }

    /**
     * Gets the value of the studentSubjects property.
     * 
     * @return
     *     possible object is
     *     {@link StudentSubjects }
     *     
     */
    public StudentSubjects getStudentSubjects() {
        return studentSubjects;
    }

    /**
     * Sets the value of the studentSubjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentSubjects }
     *     
     */
    public void setStudentSubjects(StudentSubjects value) {
        this.studentSubjects = value;
    }

}
