//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 11:55:08 PM ICT 
//


package objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}SubjectID"/&gt;
 *         &lt;element ref="{}ShortName"/&gt;
 *         &lt;element ref="{}SubjectName"/&gt;
 *         &lt;element ref="{}semester"/&gt;
 *         &lt;element ref="{}NumberOfCredit"/&gt;
 *         &lt;element ref="{}ClassID"/&gt;
 *         &lt;element ref="{}TeacherID"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subjectID",
    "shortName",
    "subjectName",
    "semester",
    "numberOfCredit",
    "classID",
    "teacherID"
})
@XmlRootElement(name = "Subject")
public class Subject {

    @XmlElement(name = "SubjectID", required = true)
    protected int subjectID;
    @XmlElement(name = "ShortName", required = true)
    protected String shortName;
    @XmlElement(name = "SubjectName", required = true)
    protected String subjectName;
    @XmlElement(required = true)
    protected String semester;
    @XmlElement(name = "NumberOfCredit", required = true)
    protected int numberOfCredit;
    @XmlElement(name = "ClassID", required = true)
    protected int classID;
    @XmlElement(name = "TeacherID", required = true)
    protected String teacherID;

    /**
     * Gets the value of the subjectID property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getSubjectID() {
        return subjectID;
    }

    /**
     * Sets the value of the subjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setSubjectID(int value) {
        this.subjectID = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the subjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * Sets the value of the subjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectName(String value) {
        this.subjectName = value;
    }

    /**
     * Gets the value of the semester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemester() {
        return semester;
    }

    /**
     * Sets the value of the semester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemester(String value) {
        this.semester = value;
    }

    /**
     * Gets the value of the numberOfCredit property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getNumberOfCredit() {
        return numberOfCredit;
    }

    /**
     * Sets the value of the numberOfCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setNumberOfCredit(int value) {
        this.numberOfCredit = value;
    }

    /**
     * Gets the value of the classID property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getClassID() {
        return classID;
    }

    /**
     * Sets the value of the classID property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setClassID(int value) {
        this.classID = value;
    }

    /**
     * Gets the value of the teacherID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherID() {
        return teacherID;
    }

    /**
     * Sets the value of the teacherID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherID(String value) {
        this.teacherID = value;
    }

}
